Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorriAndMike.Controllers
{
    public class AboutController : CorriAndMikeBaseController
    {
        [HttpPost]
        public ActionResult Wedding()
        {
            return PartialView("_Wedding");
        }

        [HttpPost]
        public ActionResult CorriAndMike()
        {
            return PartialView("_CorriAndMike");
        }

        [HttpPost]
        public ActionResult AfterParty()
        {
            return PartialView("_AfterParty");
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorriAndMike.Controllers
{
    public class EventsController : CorriAndMikeBaseController
    {
        [HttpPost]
        public ActionResult EngagementParty()
        {
            return View("_EngagementParty");
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Corri & Mike | Administration</title>
    <script src="~/Content/Scripts/jQuery/jquery-1.9.1.js"></script>
    <script src="~/Content/Scripts/jQueryUi/jquery-ui-1.10.2.custom.min.js"></script>
    <script src="~/Content/Scripts/DataTables/jquery.datatables.min.js"></script>
    <script src="~/Content/Scripts/Supersized/jquery.easing.min.js"></script>

    <link href="~/Content/Scripts/jQueryUi/css/eggplant/jquery-ui-1.10.2.custom.min.css" rel="stylesheet" />
    <link href="~/Content/Styles/DataTables/jquery.dataTables.css" rel="stylesheet"/>
    <link href="~/Content/Styles/Site.css" rel="stylesheet" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
@using CorriAndMike.Constants
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Corri & Mike's official wedding website."/>
    <title>Corri & Mike</title>
    @*<link href='http://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>*@
    <link href='http://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise' rel='stylesheet' type='text/css'>
    <script src="~/Content/Scripts/jQuery/jquery-1.9.1.js"></script>
    <script src="~/Content/Scripts/jQuery/jquery-migrate-1.2.1.js"></script>
    <script src="~/Content/Scripts/jQueryUi/jquery-ui-1.10.2.custom.min.js"></script>
    <script src="~/Content/Scripts/DataTables/jquery.datatables.min.js"></script>
    <script src="~/Content/Scripts/Supersized/supersized.core.3.2.1.min.js"></script>
    <script src="~/Content/Scripts/Supersized/jquery.easing.min.js"></script>
    <script src="~/Content/Scripts/Supersized/supersized.3.2.7.min.js"></script>
    <script src="~/Content/Scripts/qTip/jquery.qtip.min.js"></script>
    <script src="~/Content/Scripts/FlipCountDown/jquery.flipcountdown.js"></script>
    <script src="~/Content/Scripts/Countdown/jquery.countdown.js"></script>
    
    <link href="~/Content/Scripts/jQueryUi/css/eggplant/jquery-ui-1.10.2.custom.min.css" rel="stylesheet" />
    <link href="~/Content/Styles/DataTables/jquery.dataTables.css" rel="stylesheet"/>
    <link href="~/Content/Styles/Site.css" rel="stylesheet" />
    <link href="~/Content/Styles/Supersized/supersized.core.css" rel="stylesheet" />
    <link href="~/Content/Styles/Supersized/supersized.css" rel="stylesheet" />
    <link href="~/Content/Styles/Supersized/supersized.shutter.css" rel="stylesheet" />
    <link href="~/Content/Styles/qTip/jquery.qtip.min.css" rel="stylesheet" />
    <link href="~/Content/Styles/FlipCountDown/jquery.flipcountdown.css" rel="stylesheet"/>
    <link href="~/Content/Styles/Countdown/jquery.countdown.css" rel="stylesheet"/>
</head>
    <body>
        <div id="main-container">
            <div id="top-bar-container">
                <div id="top-bar">
                    <a id="show-slideshow"><span class="ui-icon ui-icon-circlesmall-minus"></span>&nbsp;<span style="text-decoration: underline;">Hide menu</span></a>
                </div>
            </div>
            <div style="clear:both;"></div>
            <div style="width: 1050px; display: block;">
                <div id="menu-container" class="ui-corner-br ui-corner-bl">
                    <img id="header-logo" src="~/Content/Images/Layout/header.png" style="margin-left: -30px;"/>
                    <ul id="menu-list">
                        <li><a id="corri-and-mike-link" class="nav-link" linkId="@(GlobalConstants.NavigationLinks.CorriAndMike)"><label class="nav-label">CORRI & MIKE</label></a></li>
                        <li><a id="wedding-link" class="nav-link" linkId="@(GlobalConstants.NavigationLinks.WeddingInStLucia)"><label class="nav-label">WEDDING IN ST. LUCIA</label></a></li>
                        <li><a id="after-party-link" class="nav-link" linkId="@(GlobalConstants.NavigationLinks.AfterParty)"><label class="nav-label">STATESIDE CELEBRATION</label></a></li>
                        <li><a id="engagement-party-link" class="nav-link" linkId="@(GlobalConstants.NavigationLinks.EngagementParty)"><label class="nav-label">ENGAGEMENT PARTY</label></a></li>
                    </ul>
                    <div id="wedding-countdown-container">
                        <h2>MARCH 23, 2015</h2>                        
                        <div id="wedding-countdown"></div>                        
                    </div>
                </div>
                    <div id="content-container" class="ui-corner-all">
                        @RenderBody()        
                    </div>
            </div>
        </div>
    
        <script type="text/javascript">
            var corriAndMikeLink = "@(GlobalConstants.NavigationLinks.CorriAndMike)";
            var weddingLink = "@(GlobalConstants.NavigationLinks.WeddingInStLucia)";
            var afterPartyLink = "@(GlobalConstants.NavigationLinks.AfterParty)";
            var engagementPartyLink = "@(GlobalConstants.NavigationLinks.EngagementParty)";

            var corriAndMikeUrl = "@(Url.Action("CorriAndMike", "About"))";
            var engagementPartyUrl = "@(Url.Action("EngagementParty", "Events"))";
            var weddingUrl = "@(Url.Action("Wedding", "About"))";
            var afterPartyUrl = "@(Url.Action("AfterParty", "About"))";

            var spinnerImgSrc = "@(Url.Content("~/Content/Images/Spinner/sprites.gif"))";
            var baseUrl = "@(Url.Content("~"))";
            var weddingDate = Math.round((new Date('3/23/2015 00:00:01')).getTime()/1000);
            $(function() {
                //$("#wedding-countdown").flipcountdown({
                //    size: "xs",
                //    showDays:true,
                //    tick: function(){
                //        var nol = function(h){
                //            return h>9?h:'0'+h;
                //        }
                //        var	range  	= 	weddingDate-Math.round((new Date()).getTime()/1000),
                //            secday	= 	86400, sechour = 3600,
                //            days	= 	parseInt(range/secday),
                //            hours	= 	parseInt((range%secday)/sechour),
                //            min	= 	parseInt(((range%secday)%sechour)/60),
                //            sec	= 	((range%secday)%sechour)%60;
                //        return nol(days)+' '+nol(hours)+' '+nol(min)+' '+nol(sec);
                //    }
                //});
            });
        </script>
        <script type="text/javascript" src="~/Content/Scripts/corriandmike.js"></script>
        @if (Request.Url.GetLeftPart(UriPartial.Authority) != "http://localhost")
        {
            <script>
                (function(i, s, o, g, r, a, m) {
                    i['GoogleAnalyticsObject'] = r;
                    i[r] = i[r] || function() {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                    a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                    a.async = 1;
                    a.src = g;
                    m.parentNode.insertBefore(a, m)
                })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

                ga('create', 'UA-41157913-1', 'corriandmike.com');
                ga('send', 'pageview');
            </script>
        }
    </body>
</html>