Models/Invitation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.WebPages.Html;

namespace CorriAndMike.Models
{
    public class Invitation
    {
        public string Id { get; set; }

        public string InvitationId { get; set; }

        public int Type { get; set; }

        public string Password { get { return "corri&mike"; } }

        public string Email { get; set; }

        public int MaxNumberOfGuests { get; set; }

        public List<string> AttendingGuests { get; set; }

        public DateTime? RsvpDate { get; set; }

        public enum InvitationType
        {
            EngagementParty,
            Wedding
        }
    }
}

ViewModels/Admin/InvitationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorriAndMike.ViewModels.Admin
{
    public class InvitationsViewModel
    {
        public IList<InvitationTableViewModel> InvitationTable { get; set; }

        public int TotalInvitedGuests { get; set; }

        public int TotalAttendingGuests { get; set; }

        public int TotalNoGuests { get; set; }

        public int TotalWaitingInvitations { get; set; }
    }
}

ViewModels/Rsvp/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorriAndMike.ViewModels.Rsvp
{
    public class LoginViewModel
    {
        public string InvitationId { get; set; }
        public string Password { get; set; }
    }
}

ViewModels/Rsvp/RsvpInvitationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CorriAndMike.Models;

namespace CorriAndMike.ViewModels.Rsvp
{
    public class RsvpInvitationViewModel
    {
        public Invitation Invitation { get; set; }

        public List<Guest> InvitationGuests { get; set; } 
    }
}

Controllers/RsvpController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CorriAndMike.Models;
using CorriAndMike.Services;
using CorriAndMike.ViewModels.Rsvp;


namespace CorriAndMike.Controllers
{
    public class RsvpController : CorriAndMikeBaseController
    {
        public ActionResult _RsvpEmail()
        {
            return View(true);
        }
        [HttpPost]
        public ActionResult Login()
        {
            return PartialView("_Login");
        }

        [HttpPost]
        public ActionResult GetInvitation(string invitationId)
        {
            var model = new RsvpInvitationViewModel();
            var invitation = RavenHelper.CurrentSession().Query<Invitation>().SingleOrDefault(i => i.InvitationId == invitationId);
            if (invitation != null)
            {
                model.Invitation = invitation;
                model.InvitationGuests = RavenHelper.CurrentSession().Query<Guest>().Where(g => g.Invitations.Any(id => id == invitation.Id)).ToList();
            }
            else
            {
                TempData["LoginError"] = "There was an error retrieving your invitation.";
                return PartialView("_Login");
            }

            return PartialView("_Invitation", model);
        }

        [HttpPost]
        public HttpResponseMessage SubmitInvitation(string invitationId, string email, string attendingGuests)
        {
            var yesGuests = attendingGuests.Split(',').Any() ? attendingGuests.Split(',').ToList() : new List<string>();
            var invitation = RavenHelper.CurrentSession().Query<Invitation>().SingleOrDefault(i => i.InvitationId == invitationId);
            var isNew = true;
            if (invitationId != null)
            {
                isNew = string.IsNullOrEmpty(invitation.Email);
                invitation.Email = email;
                invitation.RsvpDate = DateTime.Now;
                invitation.AttendingGuests.Clear();
                foreach (var guest in yesGuests.Where(yg => !string.IsNullOrEmpty(yg)))
                {
                    invitation.AttendingGuests.Add(guest);
                }
            }
            RavenHelper.SaveChanges();
            if(isNew)
                SendRsvpResponse(invitation.InvitationId, invitation.Email, yesGuests.Any(yg => !string.IsNullOrEmpty(yg)));
            SendRsvpEmailNotification(yesGuests, invitation, isNew);
            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        private void SendRsvpResponse(string invitationId, string emailAddress, bool isComing)
        {
            var email = new MailMessage { From = new MailAddress("do-not-reply@corriandmike.com", "CorriAndMike.com") };
            var bodyContent = new StringWriter();
            email.To.Add(emailAddress);
            email.Subject = string.Format("Thank you for your RSVP. (Invitation Id: {0})", invitationId);
            email.IsBodyHtml = true;
            
            var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, "_RsvpEmail");
            ViewData.Model = isComing;
            viewResult.View.Render(new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, bodyContent), bodyContent);
            
            email.Body = bodyContent.ToString();

            if (Convert.ToBoolean(ConfigurationManager.AppSettings["SendEmail"]))
                MailService.SendEmail(email);
        }
        private void SendRsvpEmailNotification(List<string> guests, Invitation invitation, bool isNew)
        {
            var email = new MailMessage { From = new MailAddress("do-not-reply@corriandmike.com", "CorriAndMike.com") };
            var bodyContent = new StringBuilder();
            var guestNames = new List<string>();
            foreach (var guestId in guests.Where(x => !string.IsNullOrEmpty(x)))
            {
                var g = RavenHelper.CurrentSession().Load<Guest>(guestId);
                guestNames.Add(g.FirstName + " " + g.LastName);
            }
            
            email.To.Add("me@mikeslevine.com");
            email.To.Add("corri.skinner@gmail.com");
            email.Subject = string.Format("Invitation {0} just {1}! ({2} attending)", invitation.InvitationId, isNew ? "RSVPed" : "updated their RSVP", guests.Count(x => !string.IsNullOrEmpty(x)) == 1 ? "1 guest" : guests.Count(x => !string.IsNullOrEmpty(x)) + " guests");
            
            email.IsBodyHtml = true;

            bodyContent.AppendFormat("Invitation {0} <br/><br/>", invitation.InvitationId);
            bodyContent.AppendFormat("Total guests invited: {0} <br/>", invitation.MaxNumberOfGuests);
            bodyContent.AppendFormat("Total guests attending: {0} <br/>", guests.Count(x => !string.IsNullOrEmpty(x)));
            bodyContent.AppendFormat("Email provided: {0} <br/>", invitation.Email);
            bodyContent.Append("Guests attending: <br/>");
            foreach (var guest in guestNames)
            {
                bodyContent.AppendFormat("&nbsp;&nbsp;&nbsp;{0}<br/>", guest);
            }
            email.Body = bodyContent.ToString();

            if(Convert.ToBoolean(ConfigurationManager.AppSettings["SendEmail"]))
                MailService.SendEmail(email);
        }
    }
}

Views/Rsvp/_Invitation.cshtml
@model CorriAndMike.ViewModels.Rsvp.RsvpInvitationViewModel

<link href="~/Content/Styles/Rsvp/rsvp.css" rel="stylesheet" />

<div id="invitation-container" class="content ui-corner-all">
    Invitation Number: @Model.Invitation.InvitationId
    <table id="rsvp-invited-guests">
        <tr>
            <td colspan="2">
                <p>
                    Corri <span style="color:#9f4d95;">&</span> Mike
                    <br/>
                    are getting married!
                    <br/>
                    Please join us in
                    <br />
                    celebrating our engagement.
                </p>
            </td>
        </tr>
        <tr>
            <td>
                <a href="http://www.ironmonkey.com"><img src="@(Url.Content("~/Content/Images/ironmonkey.jpg"))" alt="iron monkey" width="225"/></a>
            </td>
            <td >
                <address>
                    <span style="color:#9f4d95;">The Iron Monkey</span> <br/>
                    97 Greene St <br/>
                    Jersey City, NJ <br/>
                    <a id="iron-monkey-link" href="http://www.ironmonkey.com">www.ironmonkey.com</a>
                </address>
            </td>
        </tr>
    </table>
    <fieldset class="ui-corner-all" style="border: solid 1px #9F4D95;width: 95%;margin: auto;">
        <legend style="color: #CCCCFF; margin-left: 20px;">RSVP</legend>
        <div id="rsvp-response-container">
            <table>
                <tr>
                    <td style="width: 260px; vertical-align: middle;"><br />@(string.IsNullOrEmpty(Model.Invitation.Email) ? "Enter an email address" : "This is the email you gave us"):</td>
                    <td style="vertical-align: middle;"><br />@Html.TextBoxFor(m => m.Invitation.Email)</td>
                </tr>
                @foreach (var guest in Model.InvitationGuests)
                {
                    <tr>
                        <td colspan="2">
                            <table class="guest-table">
                                <tr>
                                    <td class="guest-name" style="width: 150px;">@guest.FirstName&nbsp;@guest.LastName</td>
                                    <td style="width: 250px;"><span class="rsvp-message">Yes</span>&nbsp;&nbsp;&nbsp;&nbsp;<div id="slider-@(guest.FirstName + guest.LastName)" class="rsvp-slider" guestId="@(guest.Id)"></div>&nbsp;&nbsp;&nbsp;&nbsp;<span class="rsvp-message">No</span></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
                @if(Model.InvitationGuests.Count < Model.Invitation.MaxNumberOfGuests)
                {
                    <tr>
                        <td colspan="2">
                            <table class="guest-table">
                                <tr>
                                    <td class="guest-name" style="width: 150px;"><input type="text" id="additional-guest-name" /></td>
                                    <td style="width: 250px;"><span class="rsvp-message">Yes</span>&nbsp;&nbsp;&nbsp;&nbsp;<div id="slider-plus-one" class="rsvp-slider"></div>&nbsp;&nbsp;&nbsp;&nbsp;<span class="rsvp-message">No</span></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="2" style="text-align: center;">
                        <input type="submit" id="submit-rsvp" value="Submit" /><br/>
                        <label id="rsvp-message"></label>
                        <br/>
                    </td>
                </tr>
            </table>
        </div>
    </fieldset>
</div>

<script type="text/javascript">
    var submitInvitationUrl = "@(Url.Action("SubmitInvitation"))";
    var addSingleGuestUrl = "@(Url.Content("~/api/Guest"))";
    var invitationId = "@(Model.Invitation.InvitationId)";
    var ravenInvitationId = "@(Model.Invitation.Id)";
    var attendingGuests = "@(string.Join(",", Model.Invitation.AttendingGuests))";
    
    $(function() {
        SetExistingGuestsSlider();
    });
</script>

<script src="~/Content/Scripts/Rsvp/rsvp.js"></script>

Views/Rsvp/_Login.cshtml
@model CorriAndMike.ViewModels.Rsvp.LoginViewModel

<link href="~/Content/Styles/Rsvp/rsvp.css" rel="stylesheet" />

<div id="login-container" class="content ui-corner-all">
    <div id="instructions">Please enter the number found on your invitation.</div>
    <table id="auth-table">        
        <tr><td>Invitation Number</td></tr>
        <tr><td>@Html.TextBoxFor(m => m.InvitationId)</td></tr>
        @*<tr><td>Password</td></tr>
        <tr><td>@Html.PasswordFor(m => m.Password)</td></tr>*@
        <tr><td><input type="button" id="rsvp-login" value="Login" /></td></tr>
        <tr><td><label id="login-error-msg" style="color:red; font-family: trebuchet;"></label></td></tr>
    </table>
    <br/><br/><br/>
    <div id="contact-container">
        <label style="">Having trouble? <span style="color: #CCCCFF;">Call Corri (570)-436-0554</span></label>
    </div>
</div>

<script type="text/javascript">
    var checkInvitationUrl = "@(Url.Content("~/api/Invitation"))";
    var getInvitationUrl = "@(Url.Action("GetInvitation", "Rsvp"))";
    $(function() { $("#InvitationId").focus(); });
</script>

<script src="~/Content/Scripts/Rsvp/rsvp.js"></script>

Views/Rsvp/_RsvpEmail.cshtml
@model bool
<img src="http://www.corriandmike.com/Content/Images/Layout/header.png" />
<br/>
<br/>
We received your RSVP!
<br/>
@if (Model)
{
    <p>
        We cannot wait to see you there! The information for the party is below, feel free to contact us if you have any questions and check back on the site for updates.
    </p>
    <p>
        Saturday July 6, 2013<br/>
        12:00pm - 3:00pm
    </p>
    <address>
        <span style="color:#9f4d95;">The Iron Monkey</span><br/>
        97 Greene St <br/>
        Jersey City, NJ <br/>
        <a id="iron-monkey-link" href="http://www.ironmonkey.com">www.ironmonkey.com</a>
    </address>
    <a href="http://goo.gl/maps/Zi1QW">Google Map</a>
    <br/><br/>
}
else
{
    <p>
        We are going to miss you at the party, but please come back to the website for updates.
    </p>
}
<br/>
Corri & Mike
<br/>
(570)436-0554
<br/>
<a href="mailto:corri.skinner@gmail.com">corri.skinner@gmail.com</a>
<br/>
<a href="mailTo:me@mikeslevine.com">me@mikeslevine.com</a>
<br/>
<a href="http://www.corriandmike.com">www.CorriAndMike.com</a